FROM node:lts-alpine

RUN mkdir /api && chown -R node:node /api

WORKDIR /api

COPY server/ .
COPY package.json .

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 4000

CMD node server.js
