FROM node:lts-alpine

RUN mkdir /api && chown -R node:node /api

WORKDIR /api

COPY --chown=node:node . .

RUN npm install
RUN npm run build
##RUN webpack --config  webpack.config.js

USER node

EXPOSE 3000

ENTRYPOINT ["node", "server/server.js"]
